import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Archive, ArchiveRestore, Download, Edit3, Eye, FilePlus2, FileText, Filter, Printer, Search, X } from "lucide-react";
import { PrintablePCR } from "../components/PCRWidgets";
import { loadPCRs, PCR_EDIT_KEY, printPCR, setPCRs } from "../utils/pcrStorage";

export default function PCRReports() {
  const navigate = useNavigate(); const [records, setRecords] = useState(loadPCRs); const [query, setQuery] = useState(""); const [status, setStatus] = useState("All"); const [archiveView, setArchiveView] = useState("Active"); const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => records.filter(r => (archiveView === "Archived" ? r.archived : !r.archived) && (status === "All" || r.status === status) && [r.responseNumber,r.patientName,r.placeOfIncident,r.hospitalName,r.respondingTeam].join(" ").toLowerCase().includes(query.toLowerCase())), [records, query, status, archiveView]);
  const edit = record => { sessionStorage.setItem(PCR_EDIT_KEY, record.id); navigate(`/admin/pcr/new?edit=${record.id}`); };
  const archive = record => { const next = records.map(r => r.id === record.id ? { ...r, archived: !r.archived, updatedAt: new Date().toISOString() } : r); setRecords(next); setPCRs(next); setSelected(null); };
  const doPrint = record => { setSelected(record); setTimeout(printPCR, 100); };

  return <div className="p-4 md:p-6 max-w-7xl mx-auto text-foreground">
    <div className="flex flex-wrap justify-between items-center gap-3 mb-5"><div><h1 className="text-xl font-bold flex gap-2 items-center"><FileText className="text-blue-500"/>PCR Reports</h1><p className="text-xs text-muted-foreground">View, edit, print, export, search, filter, and archive patient care reports</p></div><button onClick={()=>navigate("/admin/pcr/new")} className="px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-sm font-semibold flex gap-2 items-center"><FilePlus2 size={16}/>New PCR</button></div>
    <div className="bg-card border border-border rounded-xl p-3 mb-4 grid md:grid-cols-[1fr_auto_auto] gap-3"><label className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search response no., patient, place, hospital, or team" className="w-full pl-9 pr-3 py-2.5 bg-input-background border border-border rounded-lg text-sm"/></label><label className="flex items-center gap-2"><Filter size={15}/><select value={status} onChange={e=>setStatus(e.target.value)} className="bg-input-background border border-border rounded-lg px-3 py-2.5 text-sm"><option>All</option><option>Draft</option><option>Submitted</option><option>Verified</option><option>Rejected</option></select></label><div className="flex rounded-lg border border-border overflow-hidden">{["Active","Archived"].map(x=><button key={x} onClick={()=>setArchiveView(x)} className={`px-4 py-2 text-xs font-semibold ${archiveView===x?"bg-blue-600 text-white":"bg-secondary"}`}>{x}</button>)}</div></div>
    <div className="bg-card border border-border rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-secondary text-muted-foreground text-xs uppercase"><tr>{["Response No.","Patient","Incident","Location","Status","Updated","Actions"].map(x=><th key={x} className="text-left px-4 py-3">{x}</th>)}</tr></thead><tbody>{filtered.map(record=><tr key={record.id} className="border-t border-border hover:bg-secondary/40"><td className="px-4 py-3 font-mono text-blue-400">{record.responseNumber}</td><td className="px-4 py-3"><div className="font-semibold">{record.patientName||"Unnamed patient"}</div><div className="text-xs text-muted-foreground">{record.age&&`${record.age} yrs`} {record.gender}</div></td><td className="px-4 py-3">{record.dateOfIncident}<div className="text-xs text-muted-foreground">{record.timeOfIncident}</div></td><td className="px-4 py-3 max-w-52 truncate">{record.placeOfIncident||"-"}</td><td className="px-4 py-3"><span className={`px-2 py-1 rounded-full text-[11px] font-semibold ${record.status==="Submitted"?"bg-amber-500/15 text-amber-500":record.status==="Verified"?"bg-green-500/15 text-green-500":record.status==="Rejected"?"bg-red-500/15 text-red-500":"bg-slate-500/15 text-slate-400"}`}>{record.status}</span></td><td className="px-4 py-3 text-xs text-muted-foreground">{new Date(record.updatedAt).toLocaleString()}</td><td className="px-4 py-3"><div className="flex gap-1"><button onClick={()=>setSelected(record)} title="View" className="p-2 hover:bg-blue-500/10 text-blue-400 rounded"><Eye size={15}/></button><button onClick={()=>edit(record)} title="Edit" className="p-2 hover:bg-amber-500/10 text-amber-400 rounded"><Edit3 size={15}/></button><button onClick={()=>doPrint(record)} title="Print" className="p-2 hover:bg-green-500/10 text-green-400 rounded"><Printer size={15}/></button><button onClick={()=>doPrint(record)} title="Export PDF" className="p-2 hover:bg-violet-500/10 text-violet-400 rounded"><Download size={15}/></button><button onClick={()=>archive(record)} title={record.archived?"Restore":"Archive"} className="p-2 hover:bg-red-500/10 text-red-400 rounded">{record.archived?<ArchiveRestore size={15}/>:<Archive size={15}/>}</button></div></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="text-center py-16"><FileText size={36} className="mx-auto text-muted-foreground/30 mb-3"/><p className="font-semibold">No PCR records found</p><p className="text-xs text-muted-foreground mt-1">Create a new PCR or adjust the current filters.</p></div>}</div>
    {selected&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-3"><div className="bg-card border border-border rounded-2xl w-full max-w-6xl max-h-[95vh] flex flex-col"><div className="p-3 border-b border-border flex justify-between items-center"><div><h2 className="font-bold">{selected.responseNumber}</h2><p className="text-xs text-muted-foreground">{selected.patientName||"Unnamed patient"}</p></div><div className="flex gap-2"><button onClick={()=>edit(selected)} className="px-3 py-2 bg-secondary rounded-lg text-xs flex gap-1 items-center"><Edit3 size={14}/>Edit</button><button onClick={()=>doPrint(selected)} className="px-3 py-2 bg-blue-600 text-white rounded-lg text-xs flex gap-1 items-center"><Download size={14}/>Print / PDF</button><button onClick={()=>setSelected(null)} className="p-2 rounded-lg hover:bg-secondary"><X size={18}/></button></div></div><div className="overflow-auto bg-slate-300 p-4"><div className="max-w-[210mm] mx-auto shadow-xl"><PrintablePCR record={selected}/></div></div></div></div>}
    {selected&&<PrintablePCR record={selected} printOnly/>} 
  </div>;
}
