export const VEHICULAR_TYPES = {
  motorcycle_accident: [
    "motorcycle accident",
    "motorcycle crash",
    "motorcycle collision",
    "aksidente sa motorsiklo",
    "banggaan ng motorsiklo",
    "sumalpok ang motorsiklo",
  ],
  traffic_accident: [
    "collided",
    "crashed",
    "hit by a vehicle",
    "accident",
    "collision",
    "crash",
    "vehicular accident",
    "road accident",
    "car crash",
    "truck accident",
    "aksidente",
    "disgrasya",
    "banggaan",
    "salpukan",
    "sumalpok",
    "nasagasaan",
    "nawalan ng preno",
  ],
};
