export const PCR_CORRECTION_TARGETS = [
  { key: "response_number", label: "Response Number", step: 0, find: ["Response No."] },
  { key: "responding_team", label: "Responding Team", step: 0 },
  { key: "vehicle", label: "Vehicle / Ambulance", step: 0, find: ["Vehicle"] },
  { key: "driver", label: "Driver", step: 0 },
  { key: "main_aider", label: "Main Aider", step: 0 },
  { key: "group_leader", label: "Group Leader", step: 0 },
  { key: "assistant_aider", label: "Assistant Aider", step: 0 },
  { key: "patient_name", label: "Patient Name", step: 0 },
  { key: "patient_age", label: "Patient Age", step: 0, find: ["Age"] },
  { key: "patient_birthday", label: "Patient Birthday", step: 0, find: ["Birthday", "Date of Birth"] },
  { key: "patient_gender", label: "Patient Gender", step: 0, find: ["Gender"] },
  { key: "civil_status", label: "Civil Status", step: 0 },
  { key: "patient_address", label: "Patient Address", step: 0, find: ["Address"] },
  { key: "contact_person", label: "Contact Person", step: 0 },
  { key: "contact_number", label: "Contact Number", step: 0 },
  { key: "nature_of_call", label: "Nature of Call", step: 0 },
  { key: "date_of_incident", label: "Date of Incident", step: 0 },
  { key: "time_of_incident", label: "Time of Incident", step: 0 },
  { key: "place_of_incident", label: "Place of Incident", step: 0 },
  { key: "barangay", label: "Barangay", step: 0 },
  { key: "incident_location", label: "Exact Incident Location / Map Pin", step: 0, find: ["Exact Incident Pin", "Incident Location"] },
  { key: "dispatch_time", label: "Dispatch Time", step: 0 },
  { key: "arrival_scene", label: "Arrival at Scene", step: 1 },
  { key: "departure_scene", label: "Departure from Scene", step: 1, find: ["Departure at Scene"] },
  { key: "triage", label: "Triage", step: 1 },
  { key: "emergency_type", label: "Type of Emergency", step: 1 },
  { key: "medical_assessment", label: "Medical Assessment", step: 1 },
  { key: "trauma_assessment", label: "Trauma Assessment", step: 1 },
  { key: "chief_complaint", label: "Chief Complaint", step: 1 },
  { key: "vital_signs", label: "Vital Signs", step: 1 },
  { key: "vital_sign_time", label: "Vital Signs – Time", step: 1, find: ["Vital Sign Time"] },
  { key: "blood_pressure", label: "Vital Signs – Blood Pressure", step: 1, find: ["Blood Pressure", "BP"] },
  { key: "pulse_rate", label: "Vital Signs – Pulse Rate", step: 1, find: ["Pulse"] },
  { key: "respiratory_rate", label: "Vital Signs – Respiratory Rate", step: 1, find: ["Respiratory"] },
  { key: "temperature", label: "Vital Signs – Temperature", step: 1, find: ["Temperature"] },
  { key: "oxygen_saturation", label: "Vital Signs – Oxygen Saturation", step: 1, find: ["Oxygen", "SpO2"] },
  { key: "gcs_eye", label: "GCS – Eye Response", step: 1, find: ["Eye"] },
  { key: "gcs_verbal", label: "GCS – Verbal Response", step: 1, find: ["Verbal"] },
  { key: "gcs_motor", label: "GCS – Motor Response", step: 1, find: ["Motor"] },
  { key: "gcs", label: "GCS – Complete Assessment", step: 1, find: ["Glasgow Coma Scale", "GCS"] },
  { key: "pain_assessment", label: "Pain Assessment", step: 1 },
  { key: "body_map", label: "Body Map / Injury Location", step: 1, find: ["Body Map", "Body Mapping"] },
  { key: "medical_history", label: "Medical History", step: 2 },
  { key: "allergies", label: "Allergies", step: 2 },
  { key: "medications", label: "Medications", step: 2 },
  { key: "clinical_notes", label: "Clinical Notes / Findings", step: 2, find: ["Clinical", "Findings"] },
  { key: "interventions", label: "Treatment / Interventions", step: 3, find: ["Interventions", "Treatment"] },
  { key: "hospitalization_decision", label: "Hospitalization Decision", step: 3 },
  { key: "hospital_name", label: "Hospital / Facility Name", step: 3, find: ["Hospital Name", "Hospital / Facility"] },
  { key: "departure_hospital", label: "Departure for Hospital", step: 3 },
  { key: "arrival_hospital", label: "Arrival at Hospital", step: 3 },
  { key: "hospital_departure", label: "Departure from Hospital", step: 3 },
  { key: "back_to_base", label: "Back to Base Time", step: 3 },
  { key: "handover_receiver", label: "Patient Handover / Receiver", step: 3, find: ["Received By", "Endorsed To", "Receiver"] },
  { key: "patient_signature", label: "Patient Signature", step: 3 },
  { key: "witness_1_signature", label: "Witness 1 Signature", step: 3 },
  { key: "witness_2_signature", label: "Witness 2 Signature", step: 3 },
  { key: "attachments", label: "Attachments / Photos", step: 3, find: ["Attachments", "Photos"] },
  { key: "other", label: "Other Specific PCR Field", step: 0 },
];

export const correctionTarget = key => PCR_CORRECTION_TARGETS.find(item => item.key === key);
export const correctionStep = targets => correctionTarget(targets?.[0])?.step ?? 0;
export const correctionFindLabels = target => [target?.label, ...(target?.find || [])].filter(Boolean);
